{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-metadata-1.6.3-all.jar",
          "url": "kotlinx-coroutines-core-1.6.3-all.jar",
          "size": 86908,
          "sha512": "5f131072ccd1ee73abd32602be58fbac9a09d10b4ff60dcf2ef14133f28c629d37973542a0f2f8e30b15c16000b91412d17983eb137fb3080e32ca32f142b210",
          "sha256": "39beebac426cb9034d6f40355cf027cd523cc03929375f90716cda442d78e07e",
          "sha1": "c1e9f41068d1112d760cf8f5092f0ed0111e0275",
          "md5": "0523356ac6e417fe500d5d0a8c50a23b"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-1.6.3.jar",
          "url": "kotlinx-coroutines-core-1.6.3.jar",
          "size": 169978,
          "sha512": "86b832139eb8cf6b833bf0f7065d50c72c905c66339eee96b7b3986bb489a4825c2d556a12b32e878519a54b14e75ff51f3f68bd365ec93ac91b52723201b8e3",
          "sha256": "f1c381c5c5833c8781f9213bea9beeddebdad0020ee2bbb9f29d1fca00d51bb0",
          "sha1": "c17987358d0207357367e0eaa6e38f1e0af3cc6b",
          "md5": "f10007ba5f6d3de0a52613740ff2045c"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.6.3/kotlinx-coroutines-core-iosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.6.3/kotlinx-coroutines-core-iosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.6.3/kotlinx-coroutines-core-iosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.6.3/kotlinx-coroutines-core-iosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.6.3/kotlinx-coroutines-core-iossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iossimulatorarm64/1.6.3/kotlinx-coroutines-core-iossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.6.3/kotlinx-coroutines-core-iosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.6.3/kotlinx-coroutines-core-iosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.6.3/kotlinx-coroutines-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.6.3/kotlinx-coroutines-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.6.3/kotlinx-coroutines-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.6.3/kotlinx-coroutines-core-js-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.6.3"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.6.3/kotlinx-coroutines-core-jvm-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.6.3"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.6.3/kotlinx-coroutines-core-jvm-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.6.3"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxx64/1.6.3/kotlinx-coroutines-core-linuxx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.6.3/kotlinx-coroutines-core-macosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosarm64/1.6.3/kotlinx-coroutines-core-macosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.6.3/kotlinx-coroutines-core-macosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.6.3/kotlinx-coroutines-core-macosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.6.3/kotlinx-coroutines-core-mingwx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.6.3/kotlinx-coroutines-core-tvosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.6.3/kotlinx-coroutines-core-tvosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.6.3/kotlinx-coroutines-core-tvossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvossimulatorarm64/1.6.3/kotlinx-coroutines-core-tvossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.6.3/kotlinx-coroutines-core-tvosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.6.3/kotlinx-coroutines-core-tvosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.6.3/kotlinx-coroutines-core-watchosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.6.3/kotlinx-coroutines-core-watchosarm32-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.6.3/kotlinx-coroutines-core-watchosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.6.3/kotlinx-coroutines-core-watchosarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.6.3/kotlinx-coroutines-core-watchossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchossimulatorarm64/1.6.3/kotlinx-coroutines-core-watchossimulatorarm64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchossimulatorarm64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.6.3/kotlinx-coroutines-core-watchosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.6.3/kotlinx-coroutines-core-watchosx64-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.6.3/kotlinx-coroutines-core-watchosx86-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.6.3"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.6.3/kotlinx-coroutines-core-watchosx86-1.6.3.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.6.3"
      }
    }
  ]
}
