{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-retention",
    "version": "30.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.4.2.jar",
          "url": "android-test-plugin-host-retention-30.4.2.jar",
          "size": 44894,
          "sha512": "f164adef0ec7b9254975304d53cd3da31ad3dc41ad16cdd5be06a4417cfd4b9dc7d5003a99a781ecbaeaa44ca726b56321b2c634c80dd97bdfabfbe7854ee62e",
          "sha256": "8d58259a7ca7350456d16cdcc7b1abc7b1fefd489cd05bdf9f0f2259ff30e74b",
          "sha1": "6f607a15f7a94c2c322c6630566928e61e7eab6a",
          "md5": "45b1f679f6b9eb723fbfa2eeb9f39817"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.39.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.android.tools.emulator",
          "module": "proto",
          "version": {
            "requires": "30.4.2"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.4.2.jar",
          "url": "android-test-plugin-host-retention-30.4.2.jar",
          "size": 44894,
          "sha512": "f164adef0ec7b9254975304d53cd3da31ad3dc41ad16cdd5be06a4417cfd4b9dc7d5003a99a781ecbaeaa44ca726b56321b2c634c80dd97bdfabfbe7854ee62e",
          "sha256": "8d58259a7ca7350456d16cdcc7b1abc7b1fefd489cd05bdf9f0f2259ff30e74b",
          "sha1": "6f607a15f7a94c2c322c6630566928e61e7eab6a",
          "md5": "45b1f679f6b9eb723fbfa2eeb9f39817"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.4.2-javadoc.jar",
          "url": "android-test-plugin-host-retention-30.4.2-javadoc.jar",
          "size": 261,
          "sha512": "0fec19746d8e14a678dba1836502652fb0f8ed0a4b8436ba5b73ca8d2ec3a1cc8242119353ab9f86873b4156f3c075edeb9d31c719a5992f0e1c526cbbf819ce",
          "sha256": "04d9f89520e2b7958d615013e202be8a3aa5a5f73b44fb67d78a704bf4dd2bdc",
          "sha1": "5d1ee22c2d1a40fb7016195caaacb4df5183b371",
          "md5": "f7c80069e6e2851afd927b7a46ad19b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-retention-30.4.2-sources.jar",
          "url": "android-test-plugin-host-retention-30.4.2-sources.jar",
          "size": 12761,
          "sha512": "b6d5587a7b5200eff64c17ac8bcac34191bc4bb10dba196f2f153f0bba214612fa2350266f98f57335f91c28bde4c9666b8c3897fd22455308006399b8df5923",
          "sha256": "68aa4cf76520d2997305caebeb1ef25abeb5de34bd36c6d4201050017d92d2f5",
          "sha1": "51d5bd96111868927544bf6cfe2b9146a0a34320",
          "md5": "d5d35094c3a7935e3934044b06977087"
        }
      ]
    }
  ]
}
