{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.6.3/kotlinx-coroutines-core-1.6.3.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.6.3.jar",
          "url": "kotlinx-coroutines-core-jvm-1.6.3.jar",
          "size": 1476423,
          "sha512": "4dafbc245a0688cdff970c8f28d8361e2c2e8b928003dfc6c4f2ba4bc5db6f00f99662a62f37a4141ededa0716afc64c76335b6722ba8e8a89673f07a5c5b9c5",
          "sha256": "58a497ab595d83bbbf28892a8b34ab57d94309a8742ee0eba43cb86408d235bf",
          "sha1": "b2c2f0c8e99eac632a8db723b365bd59067cf7bd",
          "md5": "c7802d3e6a762448845ffbe6e569786c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.6.3.jar",
          "url": "kotlinx-coroutines-core-jvm-1.6.3.jar",
          "size": 1476423,
          "sha512": "4dafbc245a0688cdff970c8f28d8361e2c2e8b928003dfc6c4f2ba4bc5db6f00f99662a62f37a4141ededa0716afc64c76335b6722ba8e8a89673f07a5c5b9c5",
          "sha256": "58a497ab595d83bbbf28892a8b34ab57d94309a8742ee0eba43cb86408d235bf",
          "sha1": "b2c2f0c8e99eac632a8db723b365bd59067cf7bd",
          "md5": "c7802d3e6a762448845ffbe6e569786c"
        }
      ]
    }
  ]
}
